# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build: &base
    docker:
      - image: cimg/node:12.18
    environment:
      THUNDERBIRD_VERSION: "78.1.1"
    steps:
      - checkout
      - run: node --version
      - run: npm install
      - setup_remote_docker
      - run: ./test.sh
      - run: ./script/docker_integration_test.sh
  build-beta:
    <<: *base
    environment:
      THUNDERBIRD_VERSION: "beta"
